### ISSUE TITLE
[Feature Request] Ability to disable a row, instead of deleting it.

### ISSUE THREAD

**Issue by sstubblefield** [verbb/super-table#108]
On one of our projects, we use ST as an additional Matrix, as I'm sure many do. Our client would like to be able to disable a row, in order to come back to it later - as opposed to deleting the row and having to recreate it from scratch.

I looked all over and couldn't find this as a current feature. Let me know if it is though, and i just overlooked it. Thanks!

**Comment by engram-design** [comment]
This isn't currently possible, so will add it as a feature.

**Comment by sm9** [comment]
+1 for this feature request. I just switched a field from using Matrix to using SuperTable instead, as it looks nicer to me. But the one thing I miss is being able to enable/disable rows.

**Comment by robthompsonweb** [comment]
+1

**Comment by skramstad** [comment]
+1

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
