### ISSUE TITLE
Operation not allowed when innodb_forced_recovery > 0

### ISSUE THREAD

**Issue by wfendler** [verbb/super-table#109]
Not sure this is actually an issue or not but I'm not experiencing issues with other plugins so I'll post it.

I'm no expert in mysql/apache/php at all so when my MAMP setup got screwed up I was trying a bunch of different solutions and one that fixed it was setting innodb_forced_recovery to 2. Everything on my craft site has worked fine except for SuperTable - it seems to error out when trying to use it under this forced recovery setting.

When attempting to uninstall:

```
CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1025 Error on rename of './site/craft_supertableblocks' to './site/#sql2-c587-4e' (errno: 190 - Operation not allowed when innodb_forced_recovery > 0). The SQL statement executed was: ALTER TABLE `craft_supertableblocks` DROP FOREIGN KEY `craft_supertableblocks_fieldId_fk`
```

I also got some errors when attempting to save a new supertable field. I could get them back but I'm too nervous to screw up my MAMP setup again.

Fortunately I set it back to 0 and things seem to be working just fine now.

**Comment by engram-design** [comment]
I've not heard or come across this particular issue, but thanks for posting it. Going to leave this open for the time being if someone else has the issue so I can follow this up properly.
