### ISSUE TITLE
Translated Fields not entirely clear

### ISSUE THREAD

**Issue by kaspar-allenbach** [verbb/super-table#110]
The supertables lack a locale suffix.

I have the case that the matrix field is not translatable but the containing supertable fields are.

Current view:

![bildschirmfoto 2017-08-08 um 11 56 08](https://user-images.githubusercontent.com/762213/29066834-beb0083e-7c30-11e7-8ac2-02dd134e1ddd.png)

Better View:

![bildschirmfoto 2017-08-08 um 12 00 02](https://user-images.githubusercontent.com/762213/29066950-21626012-7c31-11e7-8d1c-b89cea37a6b5.png)
Notice the locale labels I've added to the field titles. This would also be more coherent with the standard fields.

**Comment by engram-design** [comment]
FYI, this has been added in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8) for Craft 3.
