### ISSUE TITLE
Support for Craft Search and Replace Tool?

### ISSUE THREAD

**Issue by groe** [verbb/super-table#114]
Craft provides this handy tool in the admin CP which replaces strings with other strings in all text/richtext fields - even if they are part of a Matrix field. This is especially useful for site migrations (e.g. changing the domain name etc.)

Currently (rich) text fields which are nested in a SuperTable are not searched/replaced though.

Any chance to add support for this? Does Craft provide a way for plugins to hook into this?

**Comment by engram-design** [comment]
@groe I've not actually used the Search & Replace tool, but I'll add this to the todo list. Likely to be supported in the Craft 3 version going forward.

**Comment by jkorff** [comment]
I just used the Find & Replace tool and it appears it cannot find strings within links. I wanted to replace "/resources/books/anthologies/" with "/resources/books/".

I also like to suggest to update the tool to report back what it did, or couldn't do, e.g.:

"Updated 15 entries."
"Found no entries matching your search."

Presently it just does its thing and smiles back, but I don't know what happened.

Edit: This is with Craft 3.0.21

**Comment by engram-design** [comment]
Currently there doesn't seem to be a way for plugins to access the search and replace functionality. You'll see that Craft itself has a special-case for Matrix fields, but that's all hard-coded in their code [#L58](https://github.com/craftcms/cms/blob/develop/src/queue/jobs/FindAndReplace.php#L58). We would need to do the same for Super Table, but would require hooks to modify this functionality.

@jkorff I'm not sure how well this works (again, not used this utility much), but we can't do much about the reporting back of elements - that's all 100% Craft. I'd probably suggest posting this as a feature request on the Craft Github repo.

**Comment by jkorff** [comment]
Ok, thank you for checking this, I'll do that.

**Comment by engram-design** [comment]
No movement on this with the [Craft issue](https://github.com/craftcms/cms/issues/3818)
