### ISSUE TITLE
SuperTable + LinkIt, unable to return URL only

### ISSUE THREAD

**Issue by johnfmorton** [verbb/super-table#116]
I have a site that has a content matrix which allows admins to various types of content, like a _grid_, a _heading_, _quote_, etc. One of the options is a _slideshow_ which uses a SuperTable field type with a Table Layout, which contains 3 field types per row: Assets, Plain Text (for a caption), and a LinkIt.

In the Twig template, when iterating over the rows of the SuperTable, the LinkIt field is returned as a string, not an element. This means I can only output the full HTML url structure, i.e. `<a href=http://example.com>http://example.com</a>` instead of just the URL. 

If I take the LinkIt field type outside the SuperTable, I can still access the URL only because it is still an element.

**Comment by engram-design** [comment]
@johnfmorton Not sure if I'm doing things differently, but this seems to work just fine for me.

See field setup:
<img width="636" alt="screen shot 2018-02-21 at 8 41 54 pm" src="https://user-images.githubusercontent.com/1221575/36473098-b1a160fe-1747-11e8-94bb-cb4d51450172.png">

Template:
```
{% for block in entry.matrixPageBuilder %}
    {% for row in block.slideshow %}
        URL: {{ row.linkUrl.url }}<br>
        Text: {{ row.linkUrl.text }}<br>
        {{ dump(row.linkUrl) }}
    {% endfor %}
{% endfor %}
```
Results in:
```
URL: http://craft.local/contact
Text: Contact
object(Craft\FruitLinkIt_LinkModel)
```

You'll see that using `{{ dump(row.linkUrl) }}` (`linkUrl` being the handle of the LinkIt field) returns a FruitLinkIt_LinkModel, not a string.

**Comment by engram-design** [comment]
Closing for now, but feel free to reopen if there are further issues.
