### ISSUE TITLE
Feed Me Integration 'Key "type" does not exist as the array is empty.' Error

### ISSUE THREAD

**Issue by benjaminkohl** [verbb/super-table#119]
### Description

I am experiencing an error on a Super Table template within the Feed Me _integrations template folder when I go to create a new entries JSON feed for a section that uses a Super Table field.

### Error Message

`
Key "type" does not exist as the array is empty. 

.../plugins/supertable/templates/_integrations/feedme/fields/supertable.html(5)

01 {% for blocktype in craft.superTable.getSuperTableBlocks(field.id) %}
02     {% for blocktypefield in blocktype.getFields() %}
03 
04         {# Special-case when inside Matrix #}
05         {% if parentField is defined and parentField.type == 'Matrix' %}
06             {% set handlePrefix = parentField.handle ~ '--' ~ parentBlocktype.handle ~ '--' ~ field.handle ~ '--' ~ blocktype.id ~ '--' %}
07             {% set labelName = parentField.name ~ ': ' ~ parentBlocktype.name ~ ': ' ~ field.name ~ ': ' ~ blocktypefield.name %}
08             {% set labelHandle = parentField.handle ~ '[' ~ parentBlocktype.handle ~ '][' ~ field.handle ~ '][' ~ blocktypefield.handle ~ ']' %}
09         {% else %}
10             {% set handlePrefix = field.handle ~ '--' ~ blocktype.id ~ '--' %}
11             {% set labelName = field.name ~ ': ' ~ blocktypefield.name %}
12             {% set labelHandle = field.handle ~ '[' ~ blocktypefield.handle ~ ']' %}
13         {% endif %}

`

### Steps to reproduce

1. Initiate a new JSON entries feed in Feed Me plugin.
2. Click "Save & Continue".

### Additional info

- Plugin version: 1.0.6
- Craft version: 2.6.2989

**Comment by terryupton** [comment]
I am seeing this issue too.
