### ISSUE TITLE
Feature request: Duplicate row

### ISSUE THREAD

**Issue by mmikkel** [verbb/super-table#32]
Hi there! Loving SuperTable.

Small feature request: It'd be great if it was possible to _duplicate_ a column instead of having to create a brand new one. I often find myself creating tables where every column is the same (same fieldtype, fieldtype settings etc), and it can get tedious to configure each one with exactly the same settings.

I'd propose a new "duplicate" action next to the move & delete buttons, see http://cly.mmikkel.no/image/3a1A2q0F2D0x for a quick mockup.

Keep up the good work, and thx!

**Comment by engram-design** [comment]
Nice suggestion! I'll add it to the roadmap :smiley:

**Comment by mmikkel** [comment]
Sweet!

**Comment by engram-design** [comment]
Very likely not going to happen (sorry), as we push towards a native Craft 4 solution.
