### ISSUE TITLE
Feature request: prevent duplicate relationships

### ISSUE THREAD

**Issue by juresrpcic** [verbb/super-table#38]
I'm using SuperTable as a User field. The ST acts as a many-to-many relationship between Users (users) and Companies (entries). The relationship has linking fields (user1 has invested X in company1).

SuperTable under User looks like this:
Choose company (limit selection to single Entry)  //  Capital invested (numeric field)

I'd like to check that the user doesn't add a Company twice (prevent duplicate companies).

**Comment by engram-design** [comment]
Super Table has now reached its end of life, and we'll be sticking with bug/security fixes from here on out. More in the [announcement](https://verbb.io/blog/so-long-super-table).
