### ISSUE TITLE
SQL error when trying to restore a revision where a relation has been subsequently deleted

### ISSUE THREAD

**Issue by eablokker** [verbb/super-table#65]
Here is the actual error:
`CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ennead`.`craft_relations`, CONSTRAINT`craft_relations_targetId_fk`FOREIGN KEY (`targetId`) REFERENCES`craft_elements`(`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO`craft_relations`(`fieldId`,`sourceId`,`sourceLocale`,`targetId`,`sortOrder`,`dateCreated`,`dateUpdated`,`uid`) VALUES (:row0_col0, :row0_col1, NULL, :row0_col3, :row0_col4, :row0_col5, :row0_col6, :row0_col7). Bound with :row0_col0='147', :row0_col1='9868', :row0_col3='9865', :row0_col4=1, :row0_col5='2016-04-01 22:30:03', :row0_col6='2016-04-01 22:30:03', :row0_col7='e1b9fb14-0bfb-4397-88f6-c54925fdae54'`

It happens when using a relation field in the super table. If one of the relation's entries has been deleted sometime after saving a revision, and you try to go back to that revision where the relation's entry no longer exists, and try to restore that revision, you get this error. Desired behavior should probably be to blank out the relation field if the relation no longer exists.

**Comment by engram-design** [comment]
I'll look into this (sorry for the late response). Notably, It looks like Matrix suffers from the same thing.

**Comment by engram-design** [comment]
Closing due to age/Craft 2.
