### ISSUE TITLE
Craft 3 Beta Support

### ISSUE THREAD

**Issue by pgrzyb** [verbb/super-table#99]
At this point SuperTable became a core plugin for my last few sites. As much as i would love to start working with the new Craft 3 Beta, that aint happening untill SuperTable gets ported. Any plans for that in the near future?

**Comment by engram-design** [comment]
Definitely plans, and will be supporting Super Table well into the future. Look out for it in the next month.

**Comment by pgrzyb** [comment]
Sounds great! Having a rough ETA helps a lot at this point. Looking forward to it!

**Comment by engram-design** [comment]
For sure. We use it on plenty of our projects, so pretty important too! Just wanted to wait for a little bit of the dust to settle with bugs, etc, but its next on the list. Will keep you posted.

**Comment by jbye** [comment]
Hey, just wondering if there has been any progress on this yet? Trying to decide whether to go with the Craft 3 beta or stick with 2.

**Comment by HashbangGames** [comment]
I would pay to have this expedited.  I too have been heavily reliant on Supertables and I'm now lost without it in Craft 3.  I've been building an important site, and I need them.  I actually tried to port it over myself tonight with epic failure.  LOL    I chose Craft 3 over 2.x because I don't want to have to rebuild the site in 6 months to move to Craft 3 multi-site functionality ( which I love ).

Reach out to me at marco@hashbanggames.com  and I will be happy to negotiate a rate for expediting this port to Craft 3.

**Comment by engram-design** [comment]
@HashbangGames While I appreciate everyone is keen to give Super Table (and our other plugins) a go on Craft 3, its not the actual implementation thats the issue, but supporting two versions simultaneously. Once a release is out in the wild, people will expect support and help, which is even trickier in this beta stage where things are likely to break. We're almost at the stage where this is feasible, but you'll have to be a bit patient. Rest assured, you'll have plenty of time to mess around with plugins before Craft 3 is out of beta.

I will endeavour to contact you however, if you're interested. I would imagine however, that sponsoring development would be cost-prohibitive.

**Comment by amandasaffer** [comment]
I am also interested in this. Would be great if there was just a craft3-dev branch or something, even if it's not officially supported by you guys yet.

**Comment by engram-design** [comment]
We'll provide an update on this in the next 1-2 weeks.

**Comment by astuteo** [comment]
+1 on (im)patiently waiting for SuperTable as well. It's the only plug-in that we still need for Craft 3 testing.

**Comment by astuteo** [comment]
Any updates?

**Comment by davidhellmann** [comment]
💃

**Comment by engram-design** [comment]
Super Table has finally come to Craft 3. Get it today via `composer require verbb/super-table:dev-craft-3`
